/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import javax.swing.*;
import javax.swing.border.Border;
import java.awt.*;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Random;

/**
 * @author dangd
 */
public class quizForm extends javax.swing.JFrame {

    /**
     * Creates new form quizForm
     */
    public quizForm() {
        initComponents();
        radkySouboru();
        NaplnListu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        mainPanel = new javax.swing.JPanel();
        lblVlajka = new javax.swing.JLabel();
        lblOtazka = new javax.swing.JLabel();
        btnDalsi = new javax.swing.JButton();
        btnOdpoved = new javax.swing.JButton();
        txtOdpoved = new javax.swing.JTextField();
        txtHint = new javax.swing.JTextField();
        btnHint = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(77, 97, 185));

        lblVlajka.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVlajka.setBorder(new javax.swing.border.MatteBorder(null));

        lblOtazka.setFont(new java.awt.Font("Arial", 1, 44)); // NOI18N
        lblOtazka.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOtazka.setText("Otázka");

        btnDalsi.setBackground(new java.awt.Color(213, 144, 56));
        btnDalsi.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        btnDalsi.setText("Start");
        btnDalsi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDalsi.setFocusPainted(false);
        btnDalsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDalsiActionPerformed(evt);
            }
        });

        btnOdpoved.setBackground(new java.awt.Color(51, 255, 0));
        btnOdpoved.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnOdpoved.setText("Odpověď");
        btnOdpoved.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOdpoved.setFocusPainted(false);
        btnOdpoved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdpovedActionPerformed(evt);
            }
        });

        txtOdpoved.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        txtHint.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        btnHint.setBackground(new java.awt.Color(255, 255, 0));
        btnHint.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnHint.setText("Nápověda");
        btnHint.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHint.setFocusPainted(false);
        btnHint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblOtazka, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnOdpoved, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHint, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(0, 555, Short.MAX_VALUE)
                        .addComponent(lblVlajka, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(705, 705, 705))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtOdpoved, javax.swing.GroupLayout.DEFAULT_SIZE, 1498, Short.MAX_VALUE)
                            .addComponent(txtHint))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(762, 762, 762)
                .addComponent(btnDalsi, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(btnDalsi, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158)
                .addComponent(lblOtazka)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(lblVlajka, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOdpoved, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOdpoved, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHint, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHint, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private ArrayList<Integer> listCiselRadku;
    private int cisloRadkuOtazka = 0;
    private int cisloRadkuOdpoved;
    int pocetRadku = 0;
    Random randomNumAnswer = new Random();
    private String pathOfOtazky = "src/app/otazky.txt";                 //cesta k otazkam
    private String pathOfOdpoved = "src/app/odpovedi.txt";         //cesta k odpovedim
    private String pathOfNapoveda = "src/app/napoveda.txt";      //cesta k napovedam

    //Metoda, ktera spocita radky txt souboru otazky.txt
    private void radkySouboru() {
        try (BufferedReader reader = new BufferedReader(new FileReader(pathOfOtazky))) {
            String line = reader.readLine();
            while (line != null) {
                pocetRadku++;
                line = reader.readLine();
            }
        } catch (IOException e) {
        }
    }

    // Metoda, ktera naplni list cisly od 0 az do pocet radku souboru otazky.txt(hodnotu priradi metoda 'radkySouboru'). Nasledne vygenerovany list zamicha.
    private void NaplnListu() {
        int size = pocetRadku;
        listCiselRadku = new ArrayList<Integer>();
        for (int i = 1; i <= size; i++) {
            listCiselRadku.add(i);
        }
        Collections.shuffle(listCiselRadku);
        listCiselRadku.add(999);
    }

    private void btnDalsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDalsiActionPerformed

        try {
            //kontrola jestli item z listu neni 999
            if (listCiselRadku.get(cisloRadkuOtazka) != 999) {
                //kontrola jestli radek neni prazdny
                if (!listCiselRadku.isEmpty()) {
                    int promenna = listCiselRadku.get(cisloRadkuOtazka);
                    cisloRadkuOdpoved = promenna - 1;
                    String line = Files.readAllLines(Paths.get(pathOfOtazky)).get(promenna - 1);
                    System.out.println(promenna - 1 + ", " + line);

                    //kontrola prvniho znaku kvuli vlajky
                    String kontrolniZnak = "#";
                    String otazkaSwitch = line;
                    String kontrolovanaOtazkaZnak = String.valueOf(line.charAt(0));
                    if (!kontrolovanaOtazkaZnak.equals(kontrolniZnak)) {
                        btnDalsi.setText("Další otázka");
                        lblOtazka.setText(line);
                        txtOdpoved.setText("");
                        txtHint.setText("");
                        lblVlajka.setVisible(false);
                    } else {
                        Border blackline = BorderFactory.createLineBorder(Color.black);
                        btnDalsi.setText("Další otázka");
                        
                        // SWITCH ktery podle otazkaSwitch zobrazi dany obrazek(vlajky, postavu z filmu)
                        switch (otazkaSwitch) {
                            case "#Monaco" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/vlajky/Monaco.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Belgie" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/vlajky/Belgie.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Irsko" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/vlajky/Ireland.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Cerna Hora" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/vlajky/Montenegro.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Recko" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/vlajky/Greece.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Italie" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/vlajky/Italy.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Rumunsko" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/vlajky/Rumunsko.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Belorusko" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/vlajky/Belarus.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Filipiny" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/vlajky/Filipiny.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Portugalsko" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/vlajky/Portugal.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Madagaskar" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/vlajky/Madagaskar.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Vietnam" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/vlajky/Vietnam.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Japonsko" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/vlajky/Japonsko.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Korea" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/vlajky/Korea.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Mongolsko" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/vlajky/Mongolsko.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Indie" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/vlajky/India.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Turecko" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/vlajky/Turkey.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Madarsko" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/vlajky/Hungary.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Island" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/vlajky/Iceland.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Kypr" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/vlajky/Kypr.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Vatikan" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/vlajky/Vatican.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Malta" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/vlajky/Malta.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Makedonie" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/vlajky/Makedonie.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Srbsko" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/vlajky/Srbsko.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Bosna" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/vlajky/Bosna.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Chorvatsko" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/vlajky/Croatia.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Andora" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/vlajky/Andora.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Spanelsko" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/vlajky/Spain.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Abu" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Abu.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Alfred" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Alfred.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Aragorn" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Aragorn.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Aslan" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Aslan.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Bean" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Bean.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Bella" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Bella.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Blesk" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Blesk.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Bond" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Bond.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Bonnie" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Bonnie.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Bourak" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Bourak.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Burak" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Burak.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Buzz" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Buzz.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Caroline" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Caroline.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Cervicek" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Cervicek.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Dan" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Dan.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Denerys" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Denerys.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Diego" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Diego.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Dory" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Dory.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Drago" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Drago.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Dumbo" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Dumbo.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Edward" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Edward.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Elena" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Elena.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Elizabeth" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Elizabeth.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#English" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/English.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Farquaad" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Farquaad.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Filch" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Filch.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Forest" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Forest.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Frodo" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Frodo.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Gibbs" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Gibbs.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Herold" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Herold.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Jacob" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Jacob.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Jaime" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Jaime.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Jasmina" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Jasmina.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Jeremy" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Jeremy.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Joker" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Joker.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Jones" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Jones.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Klaus" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Klaus.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Krason" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Krason.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Lincoln" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Lincoln.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Lovegood" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Lovegood.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Lucinka" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Lucinka.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Manny" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Manny.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Marty" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Marty.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Michael" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Michael.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Mike" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Mike.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Mufasa" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Mufasa.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Nemo" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Nemo.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Neo" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Neo.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Nick" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Nick.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Nicolas" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Nicolas.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Obi" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Obi.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Olivander" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Olivander.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Otik" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Otik.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Popletal" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Popletal.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Pumba" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Pumba.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Rebeka" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Rebeka.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Rocky" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Rocky.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Rowena" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Rowena.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Sara" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Sara.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Scar" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Scar.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Scrat" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Scrat.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Simba" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Simba.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Simmons" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Simmons.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Skrk" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Skrk.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Snow" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Snow.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Sparrow" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Sparrow.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Spider" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Spider.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Stark" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Stark.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Timon" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Timon.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Tumnus" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Tumnus.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Tyrion" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Tyrion.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Vader" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Vader.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Will" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Will.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Woody" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Woody.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Percy" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Percy.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Quirrell" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Quirell.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Lockhart" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Lockhart.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#George" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/George.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            case "#Kriklan" -> {
                                lblVlajka.setIcon(new ImageIcon("src/app/filmy/Kriklan.jpg"));
                                lblVlajka.setVisible(true);
                                lblVlajka.setBorder(blackline);
                            }
                            default -> {
                            }
                        }
//                        dokoncit switch na vlajky 
                        lblOtazka.setText("Co je na Obrázku?");
                        txtOdpoved.setText("");
                        txtHint.setText("");
                    }

                } else {
                    lblOtazka.setText("KONEC HRY!!!");
                }
            } else {
                //pokud item je 999 tak se vypne hra a zacne od zacatku
                lblOtazka.setText("KONEC HRY!!!");
                JOptionPane.showMessageDialog(this, "Hra skončila, klikni na 'ok' pro opakování hry", "Upozorneni", JOptionPane.ERROR_MESSAGE);
                cisloRadkuOtazka = 0;
                int promenna = listCiselRadku.get(cisloRadkuOtazka);
                String line = Files.readAllLines(Paths.get("otazky.txt")).get(promenna - 1);
                lblOtazka.setText(line);
                cisloRadkuOtazka = promenna - 1;
                lblVlajka.setVisible(false);
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Try again", "Error", JOptionPane.ERROR_MESSAGE);
            System.out.println("Něco nefunguje");
        }
        cisloRadkuOtazka++;
    }//GEN-LAST:event_btnDalsiActionPerformed

    private void btnOdpovedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdpovedActionPerformed

        try {
                // Zde se zobrazi odpoved na otazku.
                String lineOdpoved = Files.readAllLines(Paths.get(pathOfOdpoved)).get(cisloRadkuOdpoved);
                txtOdpoved.setText(lineOdpoved);
            } catch (IOException ex) {
                Logger.getLogger(quizForm.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Try again", "Error", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_btnOdpovedActionPerformed

    private void btnHintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHintActionPerformed

        // 50% sance na to, ze se ukaze odpoved, 25% sance na to, ze kdo hada, urci kdo pije, 25% sance na to ze se napije ten, kdo hada.
        int a = randomNumAnswer.nextInt(1, 12);
        String test = Integer.toString(a);
        if (a > 6) {
            if (a > 9) {
                txtHint.setText("Urči kdo pije");
            } else {
                txtHint.setText("Napí se");
            }
        } else {
            try {
                // Zde se zobrazi napoveda k otazce.
                String lineOdpoved = Files.readAllLines(Paths.get(pathOfNapoveda)).get(cisloRadkuOdpoved);
                txtHint.setText(lineOdpoved);
            } catch (IOException ex) {
                Logger.getLogger(quizForm.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Try again", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnHintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quizForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quizForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quizForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quizForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quizForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton btnDalsi;
    javax.swing.JButton btnHint;
    javax.swing.JButton btnOdpoved;
    javax.swing.JRadioButton jRadioButton1;
    javax.swing.JLabel lblOtazka;
    javax.swing.JLabel lblVlajka;
    javax.swing.JPanel mainPanel;
    javax.swing.JTextField txtHint;
    javax.swing.JTextField txtOdpoved;
    // End of variables declaration//GEN-END:variables
}
